homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyACM0
  adapter: zstack
frontend:
  port: 8381
  host: 0.0.0.0
advanced:
  log_level: debug
  channel: 25
  pan_id: 6755
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
device_options:
  legacy: false
