---

### Terrasse ###

light:

  - platform: switch
    name: "Terrasse side light"
    entity_id: switch.terrasse_light_1

  - platform: switch
    name: "Terrasse front light"
    entity_id: switch.terrasse_light_2

  - platform: group
    name: "Terrasse All Lights"
    unique_id: terrasse_all_lights
    entities:
      - light.terrasse_front_light
      - light.terrasse_side_light

  - platform: group
    name: "Terrasse and Shed Lights"
    unique_id: terrasse_and_shed_lights
    entities:
      - light.terrasse_all_lights
      - light.shed_all_lights


automation:

  - id: terrasse_turn_off_at_night
    alias: "Terrasse Lights – Turn off at night"
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: light.turn_off
        target:
          entity_id: light.terrasse_all_lights

      - service: script.automation_notification
        data:
          message: "Terrasse Lights – Turned off at night."


  - id: terrasse_light_turn_on_at_evening
    alias: "Terrasse Lights – Turn on at evening"
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.people
        state: "home"
    action:
      - service: light.turn_on
        target:
          entity_id: light.terrasse_all_lights

      - service: script.automation_notification
        data:
          message: "Terrasse Lights – Turned on at evening."


  - id: terrasse_motion_notification
    alias: "Terrasse - UniFi Protect Motion Notification"

    trigger:
      - platform: state
        entity_id:
          - binary_sensor.zapad_motion
          - binary_sensor.sever_motion
          - binary_sensor.voskhod_motion
          - binary_sensor.naves_motion
          - binary_sensor.g4_instant_person_detected
        to: "on"

    condition:
      - condition: state
        entity_id: "group.people"
        state: "not_home"

    action:
      - service: script.unifi_protect_notification
        data:
          entity_id: "{{ trigger.entity_id }}"
          message: "🚨 Motion detected on Terrasse!"
