- id: '1699406070687'
  alias: Livingroom - Turn on off lights on Movie
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light-add-on.yaml
    input:
      trigger_entities:
      - media_player.gostinaia
      trigger_on_state:
      - playing
      trigger_off_state:
      - paused
      - 'off'
      include_start_turn_off: enable_start_turn_off
      off_light_switch:
        entity_id:
        - light.livingroom_all_lights
        - light.kitchen_light
        - light.diningroom_light
        - light.hall_light
        - light.corridor_light
      include_intermission: intermission_enable
      intermission_light_switch:
        entity_id: light.livingroom_light_1
      end_snapshot_helper: input_boolean.livingroom_movie_snapshot_helper
      include_sun: sun_enabled
      light_switch:
        entity_id: light.livingroom_all_lights
- id: '1700702659103'
  alias: Link shed lights On/Off State
  description: ''
  use_blueprint:
    path: aderusha/link_multiple_devices.yaml
    input:
      linked_entities:
      - light.shed_light
      - light.shed_light_2
