substitutions:
  # tion mac address.
  tion_mac_address: "D1:74:D0:08:96:72"
  
  # name of the node.
  node_name: tion
  
  # name for main climate entity and prefix for all others.
  friendly_name: $node_name
  
  # add suffix for node name to have one firmware for many devices.
  node_add_mac_suffix: "false"
  
  # setup your board or leave it asis.
  board: esp32-s3-devkitc-1
  framework_type: esp-idf

  # wifi settings.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: master # cant use substitutions here

    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml

      ## Enable additional BLE RSSI sensor. Comment next line to disable.
      - packages/rssi_signal.yaml

      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml

      ## Uncomment next line to enable additional restart button.
      - packages/restart.yaml

      ## Common configuration settings. Do not comment or move.
      - packages/base.yaml

      ## ESP32 configuration settings. Do not comment or move.
      - packages/esp32_ble.yaml

      ## Uncomment next line to enable additional debug information.
      - packages/debug.yaml

# Enable Home Assistant API connection.
api:
  encryption:
    key: "W5D8PK//0izKMZ44FgVqQs6j/NGESx5lKPpsfMVb6ls="

esphome:
  platformio_options:
    board_build.flash_mode: dio

# WiFi hotspot configuration.
wifi:   
  ssid: $wifi_ssid
  password: $wifi_password  

  manual_ip:
    static_ip: 192.168.1.224
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Virtual port configuration
vport:
  - platform: tion_lt
    id: tion_bedroom_ble_vport
    ble_client_id: tion_ble_client

    # Optional, Do not disconnect after receiving state. Default: false.
    persistent_connection: false

    # Optional, Timeout to reconnect if no state answer received. Default: 15s.
    state_timeout: 15s

    # Optional, Allow to disable other BLE device scanning when breezer is already connected. Default: false.
    disable_scan: false

# Main climate component configuration.
climate:
  - platform: tion_lt
    id: tion_climate
    name: bedroom

    # Optional, virtual port id. Default: autodetect
    vport_id: tion_bedroom_ble_vport

    # Optional, Buzzer control switch.
    buzzer:
      name: "Buzzer"

    # Optional, Led control switch.
    led:
      name: "Led"

    # Optional, Temperatire of air before heater, °C (celsius).
    outdoor_temperature:
      name: "Outdoor Temperature"

    # Optional, Heater power, W (watt).
    heater_power:
      name: "Heater power"

    # Optional, Total airflow counter, m³ (cubic meters).
    airflow_counter:
      name: "Airflow counter"

    # Optional, Filter time left counter, days.
    filter_time_left:
      name: "Filter Time Left"

    # Optional, Filter warning state.
    filter_warnout:
      name: "Filter Warnout"

    # Optional, Tion firmware version.
    version:
      name: "Version"

    # Optional, Enable presets. Default: <empty>
    # Awailable configurable presets: home, away, boost, comfort, eco, sleep, activity.
    # Defaults:
    #   home    : { fan_speed: 2, target_temperature: 20, mode: heat }
    #   away    : { fan_speed: 1, target_temperature: 10, mode: fan_only }
    #   boost   : { fan_speed: 6, target_temperature: 10, mode: fan_only }
    #   comfort : { fan_speed: 2, target_temperature: 23, mode: heat }
    #   eco     : { fan_speed: 1, target_temperature: 16, mode: heat }
    #   sleep   : { fan_speed: 1, target_temperature: 18, mode: heat }
    #   activity: { fan_speed: 3, target_temperature: 18, mode: heat }
    # Boost is a special preset that runs for a period defined by boost_time and then switches back to the previous preset.
    presets:
      # enable and override "home" preset
      home:

      # enable "away" preset
      away:

      # enable "boost" preset
      boost:

      # enable and override "sleep" preset
      sleep:

    # Optional, configure boost time
    boost_time:
      name: "Boost Time"

    # Optional, display remaining boost time
    boost_time_left:
      name: "Boost Time Left"

    # Optional, How often query device state. Default: 60s.
    update_interval: 60s